// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxfnqgkccirllkoupdmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4Zm5xZ2tjY2lybGxrb3VwZG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTk4OTAsImV4cCI6MjA2MDAzNTg5MH0.v-kAwNcRBC5gGCzat69EOmEQq2xLrYmFm9t8X_-QMAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);